### ISSUE TITLE
LDA configuration

### ISSUE THREAD

**Issue by kyhhdm** [petuum/strads#1]
I tested strads lda on pubmed dataset in 8 nodes cluster. The program works fine.   
But it seems a little bit strange, as I find out that the cpu utilization is always near 25% on each node, whether I set the threads number to 6, 12 or 24.  
Is there any configurations that I should change to run the lda application?

**Comment by hoqirong** [comment]
Hello,

We request you use our support email to ask technical support questions:
http://petuum.github.io/contact.html

We are not using the github issue tracker for this purpose.
